version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: scraper
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
  # mongodb:
  #   image: mongo
  #   restart: always
  #   container_name: database
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

volumes:
  mongo_data: